INSERT INTO CATEGORY VALUES (1, 'FOOD', TRUE);
INSERT INTO CATEGORY VALUES (2, 'DRINKS', TRUE);
INSERT INTO CATEGORY VALUES (3, 'DESERTS', TRUE);

INSERT INTO PRODUCT VALUES (1,'P1',1.5);
INSERT INTO PRODUCT VALUES (2,'P2',1.5);
INSERT INTO PRODUCT VALUES (3,'P3',1.5);	

INSERT INTO MENU VALUES (1, 'MENU1',1);
INSERT INTO MENU VALUES (2, 'MENU2',2);
INSERT INTO MENU VALUES (3, 'MENU3',3);

	 INSERT INTO MENU_PRODUCTS VALUES (1,1);
	 INSERT INTO MENU_PRODUCTS VALUES (2,2);
	 INSERT INTO MENU_PRODUCTS VALUES (3,3);	